/**
* @package Paint Color Insert Tool
* @copyright Copyright (C) 2011 My Perfect Color. All rights reserved.
* @version 1.0
*/ 
var pci_name = 'Paint Color Insert Tool';
var pci_email = settings.pci_email;
var plugin_dir = settings.plugin_dir;

var available_brands = '<option value="all">All</option>\
<option value="3m">3m</option>\
<option value="ABC Seamless">ABC Seamless</option>\
<option value="Absolute">Absolute</option>\
<option value="Ace">Ace</option>\
<option value="Alcan">Alcan</option>\
<option value="Alcoa">Alcoa</option>\
<option value="Alexander Julian">Alexander Julian</option>\
<option value="Allway">Allway</option>\
<option value="Ameritone Devoe">Ameritone Devoe</option>\
<option value="Andersen Windows">Andersen Windows</option>\
<option value="App&more">App&more</option>\
<option value="Arroworthy">Arroworthy</option>\
<option value="Australian Standards">Australian Standards</option>\
<option value="Beacon Hill">Beacon Hill</option>\
<option value="Beckers">Beckers</option>\
<option value="Behr">Behr</option>\
<option value="Benjamin Moore">Benjamin Moore</option>\
<option value="Bercom">Bercom</option>\
<option value="Bestt Liebco">Bestt Liebco</option>\
<option value="Bob Timberlake">Bob Timberlake</option>\
<option value="Bondex">Bondex</option>\
<option value="Bondo">Bondo</option>\
<option value="Boss">Boss</option>\
<option value="British Paints">British Paints</option>\
<option value="Bruning Paints">Bruning Paints</option>\
<option value="Burger">Burger</option>\
<option value="C2">C2</option>\
<option value="Cabot">Cabot</option>\
<option value="California Paints">California Paints</option>\
<option value="Canada Hardware">Canada Hardware</option>\
<option value="Canexel">Canexel</option>\
<option value="CertainTeed">CertainTeed</option>\
<option value="Clairtone">Clairtone</option>\
<option value="Cloverdale Paint">Cloverdale Paint</option>\
<option value="Color Guild">Color Guild</option>\
<option value="Color Your World">Color Your World</option>\
<option value="ColorLife">ColorLife</option>\
<option value="Columbia Paint">Columbia Paint</option>\
<option value="Con-Lux">Con-Lux</option>\
<option value="Coronado Paints">Coronado Paints</option>\
<option value="Covalence">Covalence</option>\
<option value="Crayon Colors">Crayon Colors</option>\
<option value="Creative Homeowner">Creative Homeowner</option>\
<option value="Crown Diamond">Crown Diamond</option>\
<option value="Dal Worth Paints">Dal Worth Paints</option>\
<option value="Dap">Dap</option>\
<option value="Denalt">Denalt</option>\
<option value="Designersedge">Designersedge</option>\
<option value="Devine Color">Devine Color</option>\
<option value="Devoe & Fuller">Devoe & Fuller</option>\
<option value="Diamond Vogel Paint">Diamond Vogel Paint</option>\
<option value="Disney">Disney</option>\
<option value="Do it Best">Do it Best</option>\
<option value="Donald Kaufman">Donald Kaufman</option>\
<option value="Dqb">Dqb</option>\
<option value="Dripless">Dripless</option>\
<option value="Dulux">Dulux</option>\
<option value="Dunn Edwards">Dunn Edwards</option>\
<option value="Duron">Duron</option>\
<option value="Dutch Boy">Dutch Boy</option>\
<option value="Ecoquest">Ecoquest</option>\
<option value="Eddie Bauer">Eddie Bauer</option>\
<option value="Edgewater Industries">Edgewater Industries</option>\
<option value="Elmer">Elmer</option>\
<option value="Encore">Encore</option>\
<option value="Epiglass">Epiglass</option>\
<option value="Farrow & Ball">Farrow & Ball</option>\
<option value="Fauxlikeapro">Fauxlikeapro</option>\
<option value="Fibatape">Fibatape</option>\
<option value="Fine Paints of Europe">Fine Paints of Europe</option>\
<option value="Finnaren & Haley Paint">Finnaren & Haley Paint</option>\
<option value="Floodpro">Floodpro</option>\
<option value="Foampro">Foampro</option>\
<option value="Franklin">Franklin</option>\
<option value="Freshaire Choice">Freshaire Choice</option>\
<option value="Fuller OBrien">Fuller OBrien</option>\
<option value="Gam">Gam</option>\
<option value="Ge">Ge</option>\
<option value="General Paint">General Paint</option>\
<option value="Georgia Pacific">Georgia Pacific</option>\
<option value="Glidden">Glidden</option>\
<option value="HD Healthcare Design Research Alliance">HD Healthcare Design Research Alliance</option>\
<option value="Home Hardware">Home Hardware</option>\
<option value="Horizon Shutters">Horizon Shutters</option>\
<option value="Huls">Huls</option>\
<option value="Hunter">Hunter</option>\
<option value="Hyde">Hyde</option>\
<option value="Hydra">Hydra</option>\
<option value="ICI">ICI</option>\
<option value="Industrial Colors">Industrial Colors</option>\
<option value="Intertape">Intertape</option>\
<option value="James Hardie">James Hardie</option>\
<option value="Janovic">Janovic</option>\
<option value="Japan">Japan</option>\
<option value="Jasco">Jasco</option>\
<option value="Jen">Jen</option>\
<option value="Jones Blair">Jones Blair</option>\
<option value="Kaycan">Kaycan</option>\
<option value="Kelly Moore">Kelly Moore</option>\
<option value="Kilz">Kilz</option>\
<option value="Knight">Knight</option>\
<option value="Kolbe & Kolbe">Kolbe & Kolbe</option>\
<option value="Korea Chemical">Korea Chemical</option>\
<option value="Kravet">Kravet</option>\
<option value="Krylon">Krylon</option>\
<option value="Laura Ashley">Laura Ashley</option>\
<option value="Laurentide">Laurentide</option>\
<option value="Lutron">Lutron</option>\
<option value="MAB">MAB</option>\
<option value="Major">Major</option>\
<option value="Marshalltown">Marshalltown</option>\
<option value="Martha Stewart">Martha Stewart</option>\
<option value="Martin Senour Paints">Martin Senour Paints</option>\
<option value="Marvin Windows and Doors">Marvin Windows and Doors</option>\
<option value="Maxum">Maxum</option>\
<option value="McCormick Paints">McCormick Paints</option>\
<option value="Md">Md</option>\
<option value="MF Paints">MF Paints</option>\
<option value="Mid America Building Products">Mid America Building Products</option>\
<option value="Minwax">Minwax</option>\
<option value="Mobile Paints">Mobile Paints</option>\
<option value="Modern Masters">Modern Masters</option>\
<option value="Munsell">Munsell</option>\
<option value="Muralo">Muralo</option>\
<option value="Myperfectcolor">Myperfectcolor</option>\
<option value="N2">N2</option>\
<option value="Natural Color System">Natural Color System</option>\
<option value="Natural Magic">Natural Magic</option>\
<option value="Newell">Newell</option>\
<option value="Nickelodeon">Nickelodeon</option>\
<option value="Odor Zapp">Odor Zapp</option>\
<option value="Olympic">Olympic</option>\
<option value="Ook">Ook</option>\
<option value="Para Paints">Para Paints</option>\
<option value="Pella Windows and Doors">Pella Windows and Doors</option>\
<option value="Permatex">Permatex</option>\
<option value="Pittsburgh Paints">Pittsburgh Paints</option>\
<option value="Polypak">Polypak</option>\
<option value="Porter Paints">Porter Paints</option>\
<option value="Pratt & Lambert">Pratt & Lambert</option>\
<option value="Premier">Premier</option>\
<option value="Premier Paints">Premier Paints</option>\
<option value="Purdy">Purdy</option>\
<option value="RAL">RAL</option>\
<option value="Ralph Lauren">Ralph Lauren</option>\
<option value="Reaves">Reaves</option>\
<option value="Red Devil">Red Devil</option>\
<option value="Resene">Resene</option>\
<option value="Ressource">Ressource</option>\
<option value="Restoration Hardware">Restoration Hardware</option>\
<option value="Reynolds Siding">Reynolds Siding</option>\
<option value="Rhodes">Rhodes</option>\
<option value="Richards">Richards</option>\
<option value="Robert Allen">Robert Allen</option>\
<option value="Rodda Paint">Rodda Paint</option>\
<option value="Rollex Siding">Rollex Siding</option>\
<option value="Royal Crest">Royal Crest</option>\
<option value="Rust Oleum">Rust Oleum</option>\
<option value="Rust-Oleum">Rust-Oleum</option>\
<option value="Samson">Samson</option>\
<option value="Savogran">Savogran</option>\
<option value="Scheuder-Holland">Scheuder-Holland</option>\
<option value="Sealkrete">Sealkrete</option>\
<option value="Sears">Sears</option>\
<option value="Sherwin Williams">Sherwin Williams</option>\
<option value="Shurline">Shurline</option>\
<option value="Shurtape">Shurtape</option>\
<option value="Sico">Sico</option>\
<option value="Sikkens">Sikkens</option>\
<option value="Solver">Solver</option>\
<option value="Spontex">Spontex</option>\
<option value="Stanley">Stanley</option>\
<option value="Supreme Chemical">Supreme Chemical</option>\
<option value="Symphony">Symphony</option>\
<option value="Taubmans">Taubmans</option>\
<option value="Tikkurila">Tikkurila</option>\
<option value="Trex">Trex</option>\
<option value="True Value">True Value</option>\
<option value="TruHue">TruHue</option>\
<option value="Tuff Kote">Tuff Kote</option>\
<option value="Ultimate Paints">Ultimate Paints</option>\
<option value="US Government">US Government</option>\
<option value="USG">USG</option>\
<option value="Valspar">Valspar</option>\
<option value="Varathane">Varathane</option>\
<option value="Vista Paint">Vista Paint</option>\
<option value="Vytec">Vytec</option>\
<option value="Walmart">Walmart</option>\
<option value="Walpamur">Walpamur</option>\
<option value="Wattyl">Wattyl</option>\
<option value="Waverly">Waverly</option>\
<option value="White Knight Paint">White Knight Paint</option>\
<option value="Whizz">Whizz</option>\
<option value="Winter-Bouts">Winter-Bouts</option>\
<option value="Wolverine Siding">Wolverine Siding</option>\
<option value="Woods">Woods</option>\
<option value="Wooster">Wooster</option>\
<option value="Worthy">Worthy</option>\
<option value="Wrapon">Wrapon</option>\
<option value="Zinsser">Zinsser</option>'
	